name: "greetingMSPQ-action-test-v4"
description: a CUSTIM GITHUB ACTION TO PRINT GEETING MESSAGE

inputs:
  username:
    description: "Name of user to gree"
    required: true
  season:
    description:
    required: true
    default: Summer

outputs:
  message:
    description: "Generated greeting message"
    value: ${{ steps.greet.outputs.message }}

runs:
  using: composite
  steps:
    - name: Print geeting
      id: greet
      shell: bash
      run: |
        echo "Hello ${{ inputs.username}}, welcoe to ${{inputs.season }} season."
        echo "message=Hello ${{inputs.username}}" >> $GITHUB_OUTPUT
